### ISSUE TITLE
Question: freezing large Clojure data structures

### ISSUE THREAD

**Issue by kennethkalmer** [ptaoussanis/nippy#105]
I'm a bit baffled and need some advice please. I'm hitting a JVM limit I'm not sure how to get around:

```
#error {
 :cause "Requested array size exceeds VM limit"
 :via
 [{:type java.lang.OutOfMemoryError
   :message "Requested array size exceeds VM limit"
   :at [java.util.Arrays copyOf "Arrays.java" 3236]}]
 :trace
 [[java.util.Arrays copyOf "Arrays.java" 3236]
  [java.io.ByteArrayOutputStream grow "ByteArrayOutputStream.java" 118]
  [java.io.ByteArrayOutputStream ensureCapacity "ByteArrayOutputStream.java" 93]
  [java.io.ByteArrayOutputStream write "ByteArrayOutputStream.java" 135]
  [java.io.DataOutputStream writeByte "DataOutputStream.java" 153]
  [taoensso.nippy$write_kw invokeStatic "nippy.clj" 404]
  [taoensso.nippy$write_kw invoke "nippy.clj" 397]
  [taoensso.nippy$eval48982$fn__48983 invoke "nippy.clj" 870]
  [taoensso.nippy$eval48735$fn__48736$G__48726__48743 invoke "nippy.clj" 314]
  [taoensso.nippy$eval48790$fn__48791 invoke "nippy.clj" 331]
  [taoensso.nippy$eval48763$fn__48764$G__48754__48771 invoke "nippy.clj" 315]
  [taoensso.nippy$write_map$fn__48858$fn__48859 invoke "nippy.clj" 628]
  [taoensso.nippy$write_map$fn__48858 invoke "nippy.clj" 626]
  [clojure.lang.PersistentArrayMap kvreduce "PersistentArrayMap.java" 373]
  [clojure.core$fn__8080 invokeStatic "core.clj" 6765]
  [clojure.core$fn__8080 invoke "core.clj" 6750]
  [clojure.core.protocols$fn__7860$G__7855__7869 invoke "protocols.clj" 175]
  [clojure.core$reduce_kv invokeStatic "core.clj" 6776]
  [clojure.core$reduce_kv invoke "core.clj" 6767]
  [taoensso.nippy$write_map invokeStatic "nippy.clj" 626]
  [taoensso.nippy$write_map invoke "nippy.clj" 608]
  [taoensso.nippy$eval49018$fn__49019 invoke "nippy.clj" 884]
  [taoensso.nippy$eval48735$fn__48736$G__48726__48743 invoke "nippy.clj" 314]
  [taoensso.nippy$eval48782$fn__48783 invoke "nippy.clj" 323]
  [taoensso.nippy$eval48763$fn__48764$G__48754__48771 invoke "nippy.clj" 315]
  [taoensso.nippy$write_counted_coll$fn__48847$fn__48848 invoke "nippy.clj" 557]
  [taoensso.nippy$write_counted_coll$fn__48847 invoke "nippy.clj" 557]
  [clojure.lang.PersistentList reduce "PersistentList.java" 144]
  [clojure.core$reduce invokeStatic "core.clj" 6747]
  [clojure.core$reduce invoke "core.clj" 6730]
  [taoensso.nippy$write_counted_coll invokeStatic "nippy.clj" 557]
  [taoensso.nippy$write_counted_coll invoke "nippy.clj" 530]]}
```

This is calling `freeze-to-file`. I tried using `freeze-to-out!` as recommended in #52 and it didn't make a difference in the end.

I've had a look at #52 & #90 and it seemed to me nippy does best on vanilla Clojure data structures, so I switched from using records to just sticking with plain old maps. After switching to maps it went way better, except for two datasets that simply won't freeze and keep throwing the above exceptions.

I originally used records as a poorly implemented performance optimisation, so they weren't needed at all.

This is happening on Clojure 1.9 & Oracle JRE 1.8.0_161. 

I have no idea how to debug this any further, any advice would be appreciated.

**Comment by ptaoussanis** [comment]
Hi Kenneth,

Since this is a JVM limit, would recommend that you try googling "Requested array size exceeds VM limit" to find your options. E.g. JVM config tuning may be worth investigating: https://stackoverflow.com/questions/5497259/how-to-fix-requested-array-size-exceeds-vm-limit-error-in-java, etc.

Otherwise, I'd need more specific info to help you debug. (E.g. what do we mean by large? What is the current JVM config? How did you try `freeze-to-out!`?)

In principle, `freeze-to-out!` _should_ allow you to avoid most unnecessary large array allocations IIRC - unless some specific value in the data is itself large enough to actually already exceed the limit.

Hope that helps?

**Comment by kennethkalmer** [comment]
Thanks Peter!

I must say that at the time I don't think I was reaching for `freeze-to-out`, but I'll keep that in mind next time something like this happens and I find this thread in anger 👍 

What I did find in my case though was a vector with tons of duplicate entries (by whatever standard I assume their duplicates). The process on the other side of the serialization/deserialization process would be responsible for doing a proper deduplication. Luckily I could perform a more trivial deduplication process by simply using a set, and passing that data to nippy and it ended up working just fine.

Nippy really is a fantastically useful library, thanks so much.

**Comment by ptaoussanis** [comment]
No problem Kenneth, thanks for the follow up! 👍
