### ISSUE TITLE
Does this encode in a binary format?

### ISSUE THREAD

**Issue by didibus** [ptaoussanis/nippy#106]
From the readme, its unclear to me if this encodes into a binary format, or it creates its own human readable format?

Basically, is there any specification on the encoding? Say you wanted to be able to decode nippy encoded data from another language, what would be the work to implement such decoder?

**Comment by ptaoussanis** [comment]
Hi Didier,

That's correct, Nippy uses a binary format with a spec that was optimized for performance rather than portability between languages.

Would recommend something like edn or json or (possibly) Fressian if you have different language targets.

Hope that helps!
