### ISSUE TITLE
Support for object-array

### ISSUE THREAD

**Issue by isaksky** [ptaoussanis/nippy#113]
I'm seeing if I can make nippy work with [datascript](https://github.com/tonsky/datascript) without having to take a [slow / inefficient approach](https://github.com/tonsky/datascript/blob/c6cc4d370092077f0e61a5f3eefbb5da9c46c5b1/src/datascript/db.cljc#L594-L615), and object-array seems to be among the types that are stopping things.

Does this sound reasonable to add support for? If so, should it get its own set of type ids like byte arrays do? (E.g., `objects-[0, sm, md, lg]`?)

Btw, I see that int-arrays work, though I couldn't immediately see how (there is no `[I` class check like how there is a `[B` check for byte arrays). Is it via java serialize, edn, or something else?

**Comment by ptaoussanis** [comment]
Hi Isak,

I'm unfortunately not familiar enough with Datascript to be sure what you mean by "work with" in this context, or what the various possibilities are.

But assuming there's a decent motivation for supporting object array serialization though, I can comment on the id set question. The value of the `[0, sm, md]` prefixes is strictly as a space micro-optimization for common collection types (esp. when the collections are small).

One reasonable option would be to just to define a single `object` id type, implicitly as type `lg`. It'll be a little space inefficient for small arrays, but probably not to any degree that matters.

If there's ever a motivation to further optimize the space usage, you could introduce the other `[0, sm, md]`variants in a non-breaking way by just renaming `id-object` to `id-object-lg` at that time.

Does that make sense?

I'd probably prefer that route, just as a safe way of gauging demand for this type.

> Btw, I see that int-arrays work, though I couldn't immediately see how (there is no [I class check like how there is a [B check for byte arrays). Is it via java serialize, edn, or something else?

Not sure off hand. You could check the byte-array sequence to identify the type id being used.

Hope that helps!

**Comment by isaksky** [comment]
Makes complete sense, thanks!

**Comment by ptaoussanis** [comment]
Great, merging manually in a moment- thanks Isak!
