### ISSUE TITLE
Freezing large map

### ISSUE THREAD

**Issue by tuh8888** [ptaoussanis/nippy#118]
I have a map with 6 million entries, which I would like to save to a file. The largest value of the map has length 416. I have 20gb of memory. I am getting a heap space error. While I could increase my heap space, I feel like this shouldn't be necessary. I'm not sure why so much memory is needed to compress an object that is only 512MB.
```clojure
(nippy/freeze-to-file "file.bin" @DATA {:compressor taoensso.nippy.compression/lz4-compressor})
Execution error (OutOfMemoryError) at java.util.Arrays/copyOf (Arrays.java:3236).
Java heap space
```
```clojure
(.maxMemory (Runtime/getRuntime))
=> 20768620544
```

**Comment by tuh8888** [comment]
I don't know the details of how nippy handles it's serialization, but I was able to use Java's serialization to accomplish this task as shown below.
```clojure
(let [fileOut (java.io.FileOutputStream. file)
      out (java.io.ObjectOutputStream. fileOut)]
  (doseq [x @DATA]
    (try
      (.reset out)
      (.writeObject out x)
      (catch OutOfMemoryError e
        (print x)
        (throw e))))
  (.close out)
  (.close fileOut))
```

Notice the `(.reset out)` call. Without it, I run into the same error as above, leading me to think it might be the same issue. The call to `reset` causes the state of the ObjectOutputStream to reset because it tries to remember every object it has written, causing the memory leak.

**Comment by ptaoussanis** [comment]
Hi @tuh8888, sorry for the delayed response! Is this still an active issue?

Nippy's not using an `ObjectOutputStream`, so the issue won't be a need to call `reset`. Have you tried the same call without the LZ4 compression? That's going to incur significant additional memory usage.
