### ISSUE TITLE
freezing large clojure map with java int arrays

### ISSUE THREAD

**Issue by drorbemet** [ptaoussanis/nippy#125]
Hi, first thanks a lot for nippy.
Now how can nippy be configured or adapted to support freezing about 10GB of clojure maps with java int arrays?
With freeze-to-file I am getting an error about an unfreezable int array object 
as soon as the size of the value reaches 2GB.
Did I miss something here?

**Comment by ptaoussanis** [comment]
Hi there, sorry for the delay replying.

By default, int arrays will be serialized using Java's Serializable interface. I'm not sure if that has a limitation re: size.
If so, an alternative would be to use `extend-freeze`, `extend-thaw` to implement support via Nippy's native protocol.

Hope that helps!
