### ISSUE TITLE
No such var: enc/srng

### ISSUE THREAD

**Issue by solatis** [ptaoussanis/nippy#132]
Hi,

I think there has recently been a problem with a dependency, when upgrading nippy from 2.14.0 to 2.15.3, I am suddenly getting the error:

```
Syntax error compiling at (taoensso/nippy/crypto.clj:14:79).
No such var: enc/srng
```

According to my dependency tree, I'm using:

```
[com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"]
 overrides
[mondrian.streamer/twitter "0.0.1-SNAPSHOT"] -> [mondrian/streams "0.0.1-SNAPSHOT"] -> [com.taoensso/nippy "2.15.3"] -> [com.taoensso/encore "2.127.0"]
```

So I'm guessing it must be some intertaction between latest timbre and latest nippy that depend upon different versions of encore?

**Comment by solatis** [comment]
FYI manually overriding the encore version like

```
   [com.taoensso/timbre "4.10.0"
    :eclusions [com.taoensso/encore]]
   [com.taoensso/encore "2.127.0"]
```

fixes the issue, so I'm guessing it may be a good idea to bump the latest stable timbre version?

**Comment by ptaoussanis** [comment]
Hi there! Please see https://github.com/ptaoussanis/encore#recommended-steps-after-any-significant-dependency-update.

Timbre will be updated in the next few days 👍 

Cheers :-)
