### ISSUE TITLE
Support deftypes

### ISSUE THREAD

**Issue by optevo** [ptaoussanis/nippy#58]
Hi,

Is it possible to add support for deftyped classes? I can see you've left a data type id for them commented out. :) Looking at the class a deftype generates, it implements IType, a single constructor for all fields and a static method "getBasis" which defines the field order for the constructor so it should be possible to use reflection to read/create. I suppose I could use this to make a macro to generate the extend-freeze/extend-thaw but it would be handy to have fallback to runtime support for types that I haven't created a custom (de)serializer for (at least as an option).

**Comment by ptaoussanis** [comment]
Hi Richard, had plans to explore adding this but never got around to it (and won't have the time soon, unfortunately).

Would be very happy to see a PR that adds deftype serialization and the corresponding unit tests.

Cheers! :-)

**Comment by ptaoussanis** [comment]
Moving to #83
