### ISSUE TITLE
clojure.lang.PersistentVector$ChunkedSeq fails utils/freezable?.

### ISSUE THREAD

**Issue by chairmanwow** [ptaoussanis/nippy#59]
First off, thanks for nippy--this library has saved my bacon on many occasions.

```clojure
(utils/freezable? (clojure.lang.PersistentVector$ChunkedSeq [1 2 3] 0 0))
; => nil
```

Shouldn't this return a class? By uncommenting utils.clj:67, this appears to fix the issue, as PersistentVector$ChunkedSeq implements clojure.lang.ISeq. The value freezes and thaws just fine.

**Comment by ptaoussanis** [comment]
Hi Becker,

The trouble is that the `freezable?` util needs to be conservative: a false positive would be much worse than a false negative in this case. As a result, I've been avoiding interface checks and instead checking only for concrete types that we _know_ Nippy can freeze.

Have added `clojure.lang.PersistentVector$ChunkedSeq` as a concrete check: https://github.com/ptaoussanis/nippy/commit/af293fec7b9d6ede57da69e1a8909852b981d5d3.

Will cut a SNAPSHOT release in a moment.

Thanks for contacting me about this. Cheers :-)

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/nippy "2.8.0-SNAPSHOT"]` to Clojars.
