### ISSUE TITLE
More helpful deserialization errors for custom types

### ISSUE THREAD

**Issue by cespare** [ptaoussanis/nippy#63]
Hi @ptaoussanis,

One thing that's bitten us a couple of times is that if you serialize some record and then forget to require the record definition on the receiving end before deserializing, you get this fairly generic error:

    Thaw failed: Decryption/decompression failure, or data unfrozen/damaged.

I haven't looked at the wire format too much, but when deserialization fails would it be possible to guess that this is happening? It seems like the deserializer should be getting a class name it doesn't recognize.

Thanks!

**Comment by ptaoussanis** [comment]
Hi Caleb, that's a bug (typo in the code) - the original exception is supposed to be attached as a cause.

Thanks for the report. Will push a fixed release shortly and update here.

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/nippy "2.8.0"]` to Clojars: https://github.com/ptaoussanis/nippy/releases

Cheers! :-)

**Comment by cespare** [comment]
Nice! Thanks Peter!
