### ISSUE TITLE
Provide simple java API

### ISSUE THREAD

**Issue by mpenet** [ptaoussanis/nippy#66]
This could be useful for people wanting to use Nippy in projects that use both languages, and since the API is not very large at the moment it shouldn't require too much work.

**Comment by ptaoussanis** [comment]
Hey Max, sure - would be open to someone exploring this. Don't have any need (or free time) myself, but would be happy to take a look at ideas/PRs.

Cheers! :-)

**Comment by ptaoussanis** [comment]
Hey Max, on further reflection (+ following the same reasoning as #78) - will actually suggest that something like this would best be implemented outside Nippy itself if anyone has interest.

I don't have need of this myself, so anyway wouldn't be a good person to judge the value of any particular implementation.

Would be very happy to see (+ link to) a Java Nippy lib though! The Nippy format's been stable for a while; v2.12 is adding a bunch of optimized types - but they're optional to implement for freezing and trivial to implement for thawing.

Does that seem reasonable? Cheers! :-)
