### ISSUE TITLE
Warning: resetting Nippy thaw for custom type with id

### ISSUE THREAD

**Issue by alolis** [ptaoussanis/nippy#74]
Is this normal when I `lein uberjar`? What exactly does it mean? That my custom types were removed, or that my custom types were added?

**Comment by ptaoussanis** [comment]
Hi Alexander,

That should be fine/expected for `lein uberjar` - Lein's probably just evaluating the same namespace twice, meaning that the custom type handler is getting set, then reset (to the same value) on the second eval.

**Comment by alolis** [comment]
Good to know. It was more clear when I did the following experiment.

I have another secondary library project (mine as well) which is using nippy  and I am including the jar of that project to my main project where I have defined my custom types. If i move my custom types to the secondary project then I do not get the warning on the main project when i `lein uberjar`
