### ISSUE TITLE
nippy vs transit msgpack

### ISSUE THREAD

**Issue by klauswuestefeld** [ptaoussanis/nippy#81]
Hi,
I'm the author of Prevayler and prevayler-clj.
how would you compare nippy and transit's msgpack? Are both suited for huge amounts of data?
Thanks, Klaus

**Comment by ptaoussanis** [comment]
Hi Klaus,

> how would you compare nippy and transit's msgpack? Are both suited for
huge amounts of data?

Nippy doesn't use msgpack. Not sure what you mean by huge, but Nippy should
be fine for payloads in the gigabyte range with an appropriate hardware
environment.

Bottleneck will be how much memory you have available.

Hope that helps?

**Comment by klauswuestefeld** [comment]
> Nippy should be fine for payloads in the gigabyte range
Good to know.

Do you know how Nippy compares to transit/MsgPack in performance?

**Comment by ptaoussanis** [comment]
Sorry, I don't; haven't used Transit much myself. Shouldn't be too hard to check+compare though?

**Comment by klauswuestefeld** [comment]
OK. I'll posts results here if I get round to comparing them.

Thx

**Comment by ptaoussanis** [comment]
Awesome, thanks!

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if you have any more questions (or results to share, etc.) - cheers! :-)
