### ISSUE TITLE
Encore is required in project.clj alongside nippy, otherwise exception is thrown

### ISSUE THREAD

**Issue by Heliosmaster** [ptaoussanis/nippy#84]
If i just require nippy in my project.clj and start the REPL, this exception is thrown:

`Exception (...) Caused by: java.lang.IllegalAccessError: cond* does not exist, compiling:(taoensso/nippy.clj:1:1)`

If I require the latest version of `encore`, then it succesfully compiles.

**Comment by jeaye** [comment]
encore was properly pulled down as a dependency, for me, using lein. What are you using to manage your dependencies, @Heliosmaster?

**Comment by ptaoussanis** [comment]
Hi there, 

Sounds like you might be experiencing a dependency conflict. Please see https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md for assistance.

Cheers

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if you're still having trouble.
