### ISSUE TITLE
build failures in cljc leiningen project

### ISSUE THREAD

**Issue by SavageMessiah** [ptaoussanis/nippy#88]
When I try to build a cljc project I'm working in against nippy 2.12.1 I get this exception:

    Exception in thread "main" java.lang.IllegalAccessError: cond* does not exist, compiling:(taoensso/nippy.clj:1:1)

I'm only referencing nippy from clj files and there's no problem with 2.11.0. Maybe there's some cljc tags missing? I don't know much about this stuff, I inherited the cljc-ness from others.

**Comment by ptaoussanis** [comment]
Hi there! Would recommend checking for possible dependency conflicts, Ref. https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md.

Cheers!

**Comment by SavageMessiah** [comment]
Well that was simple! I didn't even notice this project was using timbre too. Thanks.

**Comment by SavageMessiah** [comment]
I wish this kind of thing would manifest in a way that is comprehensible.

**Comment by ptaoussanis** [comment]
No problem, cheers :-)
