### ISSUE TITLE
clojurescript support?

### ISSUE THREAD

**Issue by shaulid** [ptaoussanis/nippy#92]
Hi,

I see that there's no cljs support (no cljs/cljx). 
Is there a recommendation on how to serialize data (e.g. byte arrays) and transfer from clj server to cljs client?
Is there a way to use this library to do this?

Thanks for the lib.

**Comment by ptaoussanis** [comment]
Hey @shaulid! Please see https://github.com/ptaoussanis/nippy/issues/64

> Thanks for the lib

You're very welcome, thanks a lot for saying so- cheers :-)
