### ISSUE TITLE
Support for Schema's validation errors?

### ISSUE THREAD

**Issue by martinklepsch** [ptaoussanis/nippy#98]
```
boot -d prismatic/schema -d com.taoensso/nippy -d com.taoensso/truss repl
```
```clojure
(require 'schema.core 'taoensso.nippy)

(let [ex (try
           (schema.core/validate {:x String} {:x 1})
           (catch Throwable t
             t))]
  (taoensso.nippy/freeze {:ex ex}))
```

The above produces an exception:
```
Unfreezable type: class clojure.lang.ExceptionInfo
```
I think it is because classes cannot be fully serialized and sent over the wire so I guess this error makes sense but I'm still wondering if there's a way to make this work?

The exception data Schema attaches when using `schema.core/validate` (with some retractions):
```clojure
{:type clojure.lang.ExceptionInfo, 
 :as-str "#error {\n :cause \"Value does not match schema: {:x (not (instance? java.lang.String 1))}\"\n :data {:type :schema.core/error, :schema {:x java.lang.String}, :value {:x 1}, :error {:x (not (instance? java.lang.String 1))}}
```

**Comment by martinklepsch** [comment]
In this context it would also be nice to have a predicate function like `serializable?` to quickly filter out values that nippy does not support.

**Comment by martinklepsch** [comment]
Interestingly, converting the Throwable to a map before freezing fixes this problem:
```clojure
(let [ex (try
           (schema.core/validate {:x String} {:x 1})
           (catch Throwable t
             t))]
  (taoensso.nippy/freeze {:ex (Throwable->map ex)}))
```

**Comment by ptaoussanis** [comment]
Hi Martin!

As [mentioned](https://github.com/ptaoussanis/nippy/tree/dff8865cf8640a095f6b850ed7651165f794950b#deserializing) in the README, Nippy should support `Throwable`s, `Exception`s and `ExceptionInfo`s out-the-box.

For example:

````
(thaw (freeze (ex-info "foo" {}))) ; => ExceptionInfo
```

This is done via Nippy's `Serializable` fallback mechanism though; is it possible that you're overriding the default `*freeze-fallback*`?

> In this context it would also be nice to have a predicate function like serializable? to quickly filter out values that nippy does not support (using clojure.walk or similar).

Please see `nippy/freezable?`. Hope that helps?

Cheers :-)

**Comment by martinklepsch** [comment]
Hey Peter! 🙂 

have you tried the repro I described in the initial message? 

I was able to serialize `ExceptionInfo`s and that seems to work well but I think the ones generated by schema contain references to Java classes for which there is probably no serialization available?

`nippy/freezable?` looks good, not sure how I missed that before :)

**Comment by ptaoussanis** [comment]
> have you tried the repro I described in the initial message?

Ahh, no sorry about that- didn't have Schema installed :-)

> I was able to serialize ExceptionInfos and that seems to work well but I think the ones generated by schema contain references to Java classes for which there is probably no serialization available?

That could be an explanation. Would suggest checking the content of your `ex-data` to see what exactly is in there.

> nippy/freezable? looks good, not sure how I missed that before :)

No problem 👍 :-)

**Comment by martinklepsch** [comment]
The ex-info map contains `:schema {:x java.lang.String}` — I guess that's whats causing trouble here.

Probably, better than hacking something into nippy, it would be best if Schema provided plain edn data without references to classes etc. I'll close this and maybe open an issue against Schema later.

**Comment by ptaoussanis** [comment]
> The ex-info map contains :schema {:x java.lang.String} — I guess that's whats causing trouble here.

Hmm, are you sure?: `(thaw (freeze {:x java.lang.String})) => {:x java.lang.String}`

**Comment by martinklepsch** [comment]
Yeah you're right, it's probably not that. As the error says it's `Unfreezable type: class clojure.lang.ExceptionInfo`. Try this:

```
boot -d prismatic/schema -d com.taoensso/nippy -d com.taoensso/truss repl
```
```clojure
(require 'schema.core 'taoensso.nippy)

(let [ex (try
           (schema.core/validate {:x String} {:x 1})
           (catch Throwable t
             (def tex t)
             t))]
  (taoensso.nippy/freeze {:ex ex}))
```

Then you can inspect `tex` in the repl as well. I'm have no idea what's happening here 🙂 🙈
